# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

title: "Application Onboarding"
path: /applications-onboard/
order: 3
section:
  - title: Network Edge Applications Onboarding
    path: /doc/applications-onboard/network-edge-applications-onboarding
    meta_title: Smart Edge Open Network Edge Application On-Boarding Process
    meta_description: Smart Edge Open application on-boarding process for the Network Edge provides instructions on how to deploy an application from the Edge Controller to Edge Nodes in the cluster.

  - title: Edge DNS
    path: /doc/applications-onboard/smartedge-open-edgedns
    meta_title: Smart Edge Open Provides Edge DNS and Supports DNS Microservice
    meta_description: Smart Edge Open edge platform is required to provides access to DNS. The edge platform receives the application DNS rules from the controller.

  - title: Edge Application Agent (EAA)
    path: /doc/applications-onboard/smartedge-open-eaa
    meta_title: Edge Application Agent (EAA)
    meta_description: Smart Edge Open enables Edge Applications to produce, discover and consume services that are available on the Smart Edge Open cluster through the Edge Application Agent (EAA) APIs.

  - title: Certificate Signing
    path: /doc/applications-onboard/smartedge-open-certsigner
    meta_title: Certificate Signing
    meta_description: Each application that needs the TLS authentication certificate should generate it using the Certificate Signer by sending a CSR via Certificate Requester

  - title: Interface Service
    path: /doc/applications-onboard/smartedge-open-interface-service
    meta_title: Smart Edge Open Applications Onboard - Smart Edge Open Interface Service
    meta_description: Smart Edge Open Interface service is an application running in Kubernetes pod on every node of Smart Edge Open Kubernetes cluster and provides OVS bridge, enabling external traffic scenarios.

  - title: VM support in Smart Edge Open for Network Edge
    path: /doc/applications-onboard/smartedge-open-network-edge-vm-support
    meta_title: VM support in Smart Edge Open for Network Edge
    meta_description: VM support in Smart Edge Open for Network Edge - Setup, deployment, and management considerations.

  - title: Core Network Configuration Agent (CNCA)
    path: /doc/applications-onboard/using-smartedge-open-cnca
    meta_title: Smart Edge Open 4G/LTE Core Configuration Using CNCA
    meta_description: CNCA provides a kubectl plugin to configure the 4G/LTE Core network. Kubernetes adopts plugins concepts to extend its functionality executes CNCA related functions.
